name: Deploy React App to CWP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies & dist
        run: |
          npm install
           CI=false npm run build   # ðŸ‘ˆ CI=false taaki warnings build ko fail na kare

      - name: Zip dist files
        run: |
          tar -czvf dist.tar.gz -C dist .

      - name: Copy Zip to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22527
          source: "dist.tar.gz"
          target: "/home/jajamblo/"

      - name: Unzip files on Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22527
          script: |
            rm -rf /home/jajamblo/public_html/*
            mkdir -p /home/jajamblo/public_html
            tar -xzvf /home/jajamblo/dist.tar.gz -C /home/jajamblo/public_html
            rm /home/jajamblo/dist.tar.gz
